---
title: 'Class 6: R Functions'
author: "Ji H. Kang"
date: "4/18/2019"
output: github_document
---

### About
This is my **class 6** r markdown document with my *code* and notes for the day. 

```{r}
plot(1:10,typ="l",col="blue")
```


## Reading in files practice


There are 3 files to read.
```{r}
read.table("test1.txt", header=TRUE, sep=",")
```

```{r}
read.csv("test1.txt")
```

```{r}
read.csv("test2.txt")
```
```{r}
read.table("test2.txt", header=TRUE, sep="$")

```

```{r}
read.table("test3.txt")
```
```{r}
read.table("test3.txt")
```


## Functions
Our first silly function examlpe:
```{r}
add <- function(x,y=1) {
  # The body!!
  x + y
}

```

```{r}
add(10)
```
```{r}
add(x=1,y=4)
```
```{r}
add(1,4)
add(1)
add(c(1,2,3))
add(c(1,2,3),4)
#add(1,2,2)
```

### another example
```{r}
rescale <- function(x) {
 rng <-range(x)
 (x - rng[1]) / (rng[2] - rng[1])
}

```

```{r}
rescale(1:10)
```

```{r}
#How would you get your funciton to work here...
rescale(c(1,2,NA,3,10))
```
```{r}
# What should your function do here?
#rescale(c(1,10,"string"))
```


```{r}
x <- c(1,2,NA,3,10)
rng <- range(x,na.rm=TRUE)
(x-rng[1]/rng[2]-rng[1])
#rng
```


```{r}
rescale <- function(x){
  rng <- range(x,na.rm=TRUE)
  (x-rng[1]/rng[2]-rng[1])}
```

```{r}
rescale2 <- function(x,na.rm=TRUE){
  rng <- range(x,na.rm=na.rm)
  (x-rng[1]/rng[2]-rng[1])
}
```

Getting more 


```{r}
rescale3<- function(x, na.rm=TRUE, plot=FALSE) {
 rng <-range(x, na.rm=na.rm)
 print("Hello")
 answer <- (x - rng[1]) / (rng[2] - rng[1])
 return(answer)
 print("is it me you are looking for?")
 if(plot) {
 plot(answer, typ="b", lwd=4)
   print("Please don't sing again...")
 }
 print("I can see it in ...")
 return(answer)
}
```
```{r}
rescale3 ( c(1,3,NA,10))

```


```{r}
rescale3 ( c(1,3,NA,10), plot=TRUE)
```


```{r}
x <- c(1,10,"string")

```







