---
title: 'Class 5: R Graphics'
author: "Ji H. Kang"
output: github_document
---

```{r}
# 2A. Line plot
weight <- read.table("bimm143_05_rstats/weight_chart.txt", header=TRUE)
#header=true the V1,V2 goes away 

plot(weight$Age,weight$Weight,
     xlab="Age (months)", ylab="Weight (kg)",main="Baby Weight w/ Age",
     typ="b",
     pch=15,cex=1.5,lwd=2,
     ylim = c(2,10))
```

```{r}
#2B. Bar Plot
read.table("bimm143_05_rstats/feature_counts.txt",header=TRUE,sep="\t")
mouse <- read.table("bimm143_05_rstats/feature_counts.txt",header=TRUE,sep="\t")
barplot(mouse$Count,
        horiz = TRUE,
        ylab="",
        names.arg = mouse$Feature,
        main= "# of Features in the Mouse GCRm28 Gene",
        las=1)
barplot(mouse$Count)
#I need to argue
barplot(mouse$Count,
        names.arg = mouse$Feature)
#Rotate whole plot
barplot(mouse$Count,names.arg = mouse$Feature,
        horiz=TRUE)
#Fix label 
barplot(mouse$Count,names.arg = mouse$Feature,horiz=TRUE,
        las=1)
#Fix parameter: cannot see the full label PAR
par(mar=c(3.1, 11.1, 4.1, 2))
barplot(mouse$Count,names.arg = mouse$Feature,horiz=TRUE, las=1)

#Name of bar and range
par(mar=c(3.1, 11.1, 4.1, 2))
barplot(mouse$Count,names.arg = mouse$Feature,horiz=TRUE, las=1, xlim=c(0,80000),
        main="Number of Features in the Mouse GRCm38 Genome")

```

```{r}

#Section 3: Using Color in Plots

#3A. Providing color vectors
counts <- read.table("bimm143_05_rstats/male_female_counts.txt",
                     sep="\t", header=TRUE)
# read delim <- convenience (format already encoded)
counts <- read.delim("bimm143_05_rstats/male_female_counts.txt")

barplot(counts$Count, names.arg = counts$Sample,
        las=2,
        col=c("red","blue"))

barplot(counts$Count, names.arg = counts$Sample,las=2,
        col=rainbow(10))

barplot(counts$Count, names.arg = counts$Sample,las=2,
        col=heat.colors(10))

```

